version: '3.4'
services:
  cursesapi:
    image: ${DOCKER_REGISTRY-}cursesapi
    build:
      context: .
      dockerfile: CursesAPI/Dockerfile
    depends_on:
      - sqldata
    ports:
      - "5081:80"
  studentsapi:
    image: ${DOCKER_REGISTRY-}studentsapi
    build:
      context: .
      dockerfile: StudentsAPI/Dockerfile
    depends_on:
      - sqldata
    ports:
      - "5082:80"
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sa
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
        